plugin: aws_ec2
boto_profile: default
regions:
  - us-east-1
strict: False

# filters:
#   tag:Env: Terraform

strict_permissions: False

keyed_groups:
 # Add hosts to tag_Name_Value groups for each Name/Value tag pair
  - prefix: tag
    key: tags

hostnames:
  - ip-address
  - dns-name
